[package]
name = "rust"
version = "0.1.0"
authors = ["Nomann Ali <engr.nomiabbasi@gmail.com>"]
edition = "2021"
publish = false

[workspace]
members = [".", "actix", "getting-started-rust", "seaorm"]

[dependencies]
